# IMPORTING LIBRARIES

In [284]:
import pandas as pd
from scipy import stats
import numpy as np
import os
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score

In [285]:
file_path = 'WA_Fn-UseC_-HR-Employee-Attrition.csv'
df = pd.read_csv(file_path)

# Load the dataset

In [286]:
df = pd.read_csv("WA_Fn-UseC_-HR-Employee-Attrition.csv")

# Data Exploration

In [287]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [288]:
df.tail()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [289]:
df.shape

(1470, 35)

In [290]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [291]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [292]:
print(df.describe(include='all'))

                Age Attrition BusinessTravel    DailyRate  \
count   1470.000000      1470           1470  1470.000000
unique          NaN         2              3          NaN
top             NaN        No  Travel_Rarely          NaN
freq            NaN      1233           1043          NaN
mean      36.923810       NaN            NaN   802.485714
std        9.135373       NaN            NaN   403.509100
min       18.000000       NaN            NaN   102.000000
25%       30.000000       NaN            NaN   465.000000
50%       36.000000       NaN            NaN   802.000000
75%       43.000000       NaN            NaN  1157.000000
max       60.000000       NaN            NaN  1499.000000

                    Department  DistanceFromHome    Education EducationField  \
count                     1470       1470.000000  1470.000000           1470
unique                       3               NaN          NaN              6
top     Research & Development               NaN          NaN  Life Sciences
freq                       961               NaN          NaN            606
mean                       NaN          9.192517     2.912925            NaN
std                        NaN          8.106864     1.024165            NaN
min                        NaN          1.000000     1.000000            NaN
25%                        NaN          2.000000     2.000000            NaN
50%                        NaN          7.000000     3.000000            NaN
75%                        NaN         14.000000     4.000000            NaN
max                        NaN         29.000000     5.000000            NaN

        EmployeeCount  EmployeeNumber  ...  RelationshipSatisfaction  \
count          1470.0     1470.000000  ...               1470.000000
unique            NaN             NaN  ...                       NaN
top               NaN             NaN  ...                       NaN
freq              NaN             NaN  ...                       NaN
mean              1.0     1024.865306  ...                  2.712245
std               0.0      602.024335  ...                  1.081209
min               1.0        1.000000  ...                  1.000000
25%               1.0      491.250000  ...                  2.000000
50%               1.0     1020.500000  ...                  3.000000
75%               1.0     1555.750000  ...                  4.000000
max               1.0     2068.000000  ...                  4.000000

       StandardHours  StockOptionLevel  TotalWorkingYears  \
count         1470.0       1470.000000        1470.000000
unique           NaN               NaN                NaN
top              NaN               NaN                NaN
freq             NaN               NaN                NaN
mean            80.0          0.793878          11.279592
std              0.0          0.852077           7.780782
min             80.0          0.000000           0.000000
25%             80.0          0.000000           6.000000
50%             80.0          1.000000          10.000000
75%             80.0          1.000000          15.000000
max             80.0          3.000000          40.000000

        TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  \
count             1470.000000     1470.000000     1470.000000
unique                    NaN             NaN             NaN
top                       NaN             NaN             NaN
freq                      NaN             NaN             NaN
mean                 2.799320        2.761224        7.008163
std                  1.289271        0.706476        6.126525
min                  0.000000        1.000000        0.000000
25%                  2.000000        2.000000        3.000000
50%                  3.000000        3.000000        5.000000
75%                  3.000000        3.000000        9.000000
max                  6.000000        4.000000       40.000000

       YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager
count         1470.000000              1470.000000           1470.000000
unique                NaN                      NaN                   NaN
top                   NaN                      NaN                   NaN
freq                  NaN                      NaN                   NaN
mean             4.229252                 2.187755              4.123129
std              3.623137                 3.222430              3.568136
min              0.000000                 0.000000              0.000000
25%              2.000000                 0.000000              2.000000
50%              3.000000                 1.000000              3.000000
75%              7.000000                 3.000000              7.000000
max             18.000000                15.000000             17.000000

[11 rows x 35 columns]

In [293]:
print(df.isnull().sum())

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [294]:
for col in df.describe(include = 'object').columns:
    print(col)
    print(df[col].unique())
    print('-'*50)

Attrition
['Yes' 'No']
--------------------------------------------------
BusinessTravel
['Travel_Rarely' 'Travel_Frequently' 'Non-Travel']
--------------------------------------------------
Department
['Sales' 'Research & Development' 'Human Resources']
--------------------------------------------------
EducationField
['Life Sciences' 'Other' 'Medical' 'Marketing' 'Technical Degree'
 'Human Resources']
--------------------------------------------------
Gender
['Female' 'Male']
--------------------------------------------------
JobRole
['Sales Executive' 'Research Scientist' 'Laboratory Technician'
 'Manufacturing Director' 'Healthcare Representative' 'Manager'
 'Sales Representative' 'Research Director' 'Human Resources']
--------------------------------------------------
MaritalStatus
['Single' 'Married' 'Divorced']
--------------------------------------------------
Over18
['Y']
--------------------------------------------------
OverTime
['Yes' 'No']
--------------------------------------------------

In [295]:
for col in df.select_dtypes(include=['object']).columns:
    print(col, df[col].unique())

Attrition ['Yes' 'No']
BusinessTravel ['Travel_Rarely' 'Travel_Frequently' 'Non-Travel']
Department ['Sales' 'Research & Development' 'Human Resources']
EducationField ['Life Sciences' 'Other' 'Medical' 'Marketing' 'Technical Degree'
 'Human Resources']
Gender ['Female' 'Male']
JobRole ['Sales Executive' 'Research Scientist' 'Laboratory Technician'
 'Manufacturing Director' 'Healthcare Representative' 'Manager'
 'Sales Representative' 'Research Director' 'Human Resources']
MaritalStatus ['Single' 'Married' 'Divorced']
Over18 ['Y']
OverTime ['Yes' 'No']

In [296]:
Q1 = df['MonthlyIncome'].quantile(0.25)
Q3 = df['MonthlyIncome'].quantile(0.75)
IQR = Q3 - Q1
df = df[(df['MonthlyIncome'] >= (Q1 - 1.5 * IQR)) & (df['MonthlyIncome'] <= (Q3 + 1.5 * IQR))]

In [297]:
df_encoded = pd.get_dummies(df, columns=['BusinessTravel', 'Department', 'EducationField', 'Gender', 'JobRole', 'MaritalStatus', 'OverTime'])

In [298]:
# Data Labeling
df_encoded['Attrition'] = df_encoded['Attrition'].apply(lambda x: 1 if x == 'Yes' else 0)

In [299]:
# Define features and target variable
X = df.drop(columns=['Attrition'])
y = df['Attrition']

In [300]:
# Define categorical and numerical features
categorical_features = ['Gender', 'Department', 'MaritalStatus']
numeric_features = ['Age', 'MonthlyIncome', 'YearsAtCompany']

In [301]:
# Create preprocessing pipeline
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_features),
        ('cat', OneHotEncoder(), categorical_features)
    ]
)

In [302]:
# Define the model pipeline
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(random_state=42))
])

In [303]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [304]:
# Train the model
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['Age', 'MonthlyIncome',
                                                   'YearsAtCompany']),
                                                 ('cat', OneHotEncoder(),
                                                  ['Gender', 'Department',
                                                   'MaritalStatus'])])),
                ('classifier', RandomForestClassifier(random_state=42))])

In [305]:
# Make predictions
y_pred = model.predict(X_test)

In [306]:
# Evaluate model performance
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

Accuracy: 0.81

In [307]:
# Save the predictions
predictions_df = X_test.copy()
predictions_df['ActualAttrition'] = y_test
predictions_df['PredictedAttrition'] = y_pred

In [308]:
# Save to CSV
predictions_df.to_csv('predicted_attrition.csv', index=False)

In [309]:
df = pd.read_csv('predicted_attrition.csv')

In [310]:
df.head()

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,...,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,ActualAttrition,PredictedAttrition
0,44,Travel_Rarely,1488,Sales,1,5,Marketing,1,68,2,...,1,9,2,2,4,3,1,3,No,No
1,28,Travel_Rarely,736,Sales,26,3,Life Sciences,1,1387,3,...,1,5,0,3,5,3,0,4,No,No
2,32,Travel_Rarely,234,Sales,1,4,Medical,1,2013,2,...,1,3,2,3,2,2,2,2,No,No
3,34,Non-Travel,1381,Sales,4,4,Marketing,1,523,3,...,1,6,3,3,3,2,1,2,No,No
4,31,Travel_Rarely,182,Research & Development,8,5,Life Sciences,1,1430,1,...,0,9,3,4,3,2,1,0,No,No